export const ERR_CODES = {
    CUSTOM: 'LADYBUG_ERR',
    NETWORK_ERR: 'LADYBUG_NETWORK_ERR',
    TIMEOUT: 'LADYBUG_TIMEOUT_ERR',
    ABORTED: 'LADYBUG_ABORTED',
    INVALID_RESPONSE: 'LADYBUG_INVALID_RES',
    INVALID_REQUEST: 'LADYBUG_INVALID_REQ',
    CANCELED: 'LADYBUG_CANCELLED_ERR',
    NOT_SUPPORTED: 'LADYBUG_ERR_NOT_SUPPORTED',
    INVALID_URL: 'LADYBUG_ERR_INVALID_URI/URL'
}